/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Badge {
  'owner' : UserId,
  'badgeType' : BadgeType,
  'earnedAt' : Timestamp,
}
export type BadgeType = { 'MonthlyOnTrack' : null } |
  { 'FirstBudget' : null } |
  { 'LoggingStreak7' : null };
export interface Budget {
  'owner' : UserId,
  'categoryLimits' : CategoryLimits,
  'totalAmount' : number,
}
export type Category = { 'Food' : null } |
  { 'Health' : null } |
  { 'Bills' : null } |
  { 'Entertainment' : null } |
  { 'Shopping' : null } |
  { 'Other' : null } |
  { 'Transport' : null };
export interface CategoryLimits {
  'other' : [] | [number],
  'entertainment' : [] | [number],
  'food' : [] | [number],
  'transport' : [] | [number],
  'bills' : [] | [number],
  'shopping' : [] | [number],
  'health' : [] | [number],
}
export interface Expense {
  'id' : ExpenseId,
  'owner' : UserId,
  'date' : Timestamp,
  'note' : [] | [string],
  'category' : Category,
  'amount' : number,
}
export type ExpenseId = string;
export type FinancialGoal = { 'BuildWealth' : null } |
  { 'TrackSpending' : null } |
  { 'SaveForPurchase' : null } |
  { 'PayOffDebt' : null } |
  { 'Other' : null } |
  { 'SaveForEmergencies' : null };
export type GoalId = string;
export type ProfessionStatus = { 'BusinessMan' : null } |
  { 'Employee' : null } |
  { 'Student' : null } |
  { 'Other' : null } |
  { 'Freelancer' : null } |
  { 'Entrepreneur' : null };
export interface SavingsGoalPublic {
  'id' : GoalId,
  'owner' : UserId,
  'name' : string,
  'targetAmount' : number,
  'targetDate' : Timestamp,
  'currentAmount' : number,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'financialGoals' : [] | [Array<FinancialGoal>],
  'createdAt' : Timestamp,
  'professionStatus' : [] | [ProfessionStatus],
  'onboardingCompleted' : boolean,
}
export interface _SERVICE {
  'addExpense' : ActorMethod<
    [ExpenseId, number, Category, [] | [string], Timestamp],
    Expense
  >,
  'createGoal' : ActorMethod<
    [GoalId, string, number, number, Timestamp],
    SavingsGoalPublic
  >,
  'deleteExpense' : ActorMethod<[ExpenseId], boolean>,
  'deleteGoal' : ActorMethod<[GoalId], boolean>,
  'getBadges' : ActorMethod<[], Array<Badge>>,
  'getBudget' : ActorMethod<[], [] | [Budget]>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'getExpensesByMonth' : ActorMethod<[bigint, bigint], Array<Expense>>,
  'getGoals' : ActorMethod<[], Array<SavingsGoalPublic>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'saveUserProfile' : ActorMethod<
    [[] | [ProfessionStatus], [] | [Array<FinancialGoal>], boolean],
    undefined
  >,
  'setBudget' : ActorMethod<[number, CategoryLimits], Budget>,
  'updateGoalProgress' : ActorMethod<
    [GoalId, number],
    [] | [SavingsGoalPublic]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];