/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExpenseId = IDL.Text;
export const Category = IDL.Variant({
  'Food' : IDL.Null,
  'Health' : IDL.Null,
  'Bills' : IDL.Null,
  'Entertainment' : IDL.Null,
  'Shopping' : IDL.Null,
  'Other' : IDL.Null,
  'Transport' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Expense = IDL.Record({
  'id' : ExpenseId,
  'owner' : UserId,
  'date' : Timestamp,
  'note' : IDL.Opt(IDL.Text),
  'category' : Category,
  'amount' : IDL.Float64,
});
export const GoalId = IDL.Text;
export const SavingsGoalPublic = IDL.Record({
  'id' : GoalId,
  'owner' : UserId,
  'name' : IDL.Text,
  'targetAmount' : IDL.Float64,
  'targetDate' : Timestamp,
  'currentAmount' : IDL.Float64,
});
export const BadgeType = IDL.Variant({
  'MonthlyOnTrack' : IDL.Null,
  'FirstBudget' : IDL.Null,
  'LoggingStreak7' : IDL.Null,
});
export const Badge = IDL.Record({
  'owner' : UserId,
  'badgeType' : BadgeType,
  'earnedAt' : Timestamp,
});
export const CategoryLimits = IDL.Record({
  'other' : IDL.Opt(IDL.Float64),
  'entertainment' : IDL.Opt(IDL.Float64),
  'food' : IDL.Opt(IDL.Float64),
  'transport' : IDL.Opt(IDL.Float64),
  'bills' : IDL.Opt(IDL.Float64),
  'shopping' : IDL.Opt(IDL.Float64),
  'health' : IDL.Opt(IDL.Float64),
});
export const Budget = IDL.Record({
  'owner' : UserId,
  'categoryLimits' : CategoryLimits,
  'totalAmount' : IDL.Float64,
});
export const FinancialGoal = IDL.Variant({
  'BuildWealth' : IDL.Null,
  'TrackSpending' : IDL.Null,
  'SaveForPurchase' : IDL.Null,
  'PayOffDebt' : IDL.Null,
  'Other' : IDL.Null,
  'SaveForEmergencies' : IDL.Null,
});
export const ProfessionStatus = IDL.Variant({
  'BusinessMan' : IDL.Null,
  'Employee' : IDL.Null,
  'Student' : IDL.Null,
  'Other' : IDL.Null,
  'Freelancer' : IDL.Null,
  'Entrepreneur' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'financialGoals' : IDL.Opt(IDL.Vec(FinancialGoal)),
  'createdAt' : Timestamp,
  'professionStatus' : IDL.Opt(ProfessionStatus),
  'onboardingCompleted' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addExpense' : IDL.Func(
      [ExpenseId, IDL.Float64, Category, IDL.Opt(IDL.Text), Timestamp],
      [Expense],
      [],
    ),
  'createGoal' : IDL.Func(
      [GoalId, IDL.Text, IDL.Float64, IDL.Float64, Timestamp],
      [SavingsGoalPublic],
      [],
    ),
  'deleteExpense' : IDL.Func([ExpenseId], [IDL.Bool], []),
  'deleteGoal' : IDL.Func([GoalId], [IDL.Bool], []),
  'getBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
  'getBudget' : IDL.Func([], [IDL.Opt(Budget)], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getExpensesByMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getGoals' : IDL.Func([], [IDL.Vec(SavingsGoalPublic)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'saveUserProfile' : IDL.Func(
      [IDL.Opt(ProfessionStatus), IDL.Opt(IDL.Vec(FinancialGoal)), IDL.Bool],
      [],
      [],
    ),
  'setBudget' : IDL.Func([IDL.Float64, CategoryLimits], [Budget], []),
  'updateGoalProgress' : IDL.Func(
      [GoalId, IDL.Float64],
      [IDL.Opt(SavingsGoalPublic)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExpenseId = IDL.Text;
  const Category = IDL.Variant({
    'Food' : IDL.Null,
    'Health' : IDL.Null,
    'Bills' : IDL.Null,
    'Entertainment' : IDL.Null,
    'Shopping' : IDL.Null,
    'Other' : IDL.Null,
    'Transport' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Expense = IDL.Record({
    'id' : ExpenseId,
    'owner' : UserId,
    'date' : Timestamp,
    'note' : IDL.Opt(IDL.Text),
    'category' : Category,
    'amount' : IDL.Float64,
  });
  const GoalId = IDL.Text;
  const SavingsGoalPublic = IDL.Record({
    'id' : GoalId,
    'owner' : UserId,
    'name' : IDL.Text,
    'targetAmount' : IDL.Float64,
    'targetDate' : Timestamp,
    'currentAmount' : IDL.Float64,
  });
  const BadgeType = IDL.Variant({
    'MonthlyOnTrack' : IDL.Null,
    'FirstBudget' : IDL.Null,
    'LoggingStreak7' : IDL.Null,
  });
  const Badge = IDL.Record({
    'owner' : UserId,
    'badgeType' : BadgeType,
    'earnedAt' : Timestamp,
  });
  const CategoryLimits = IDL.Record({
    'other' : IDL.Opt(IDL.Float64),
    'entertainment' : IDL.Opt(IDL.Float64),
    'food' : IDL.Opt(IDL.Float64),
    'transport' : IDL.Opt(IDL.Float64),
    'bills' : IDL.Opt(IDL.Float64),
    'shopping' : IDL.Opt(IDL.Float64),
    'health' : IDL.Opt(IDL.Float64),
  });
  const Budget = IDL.Record({
    'owner' : UserId,
    'categoryLimits' : CategoryLimits,
    'totalAmount' : IDL.Float64,
  });
  const FinancialGoal = IDL.Variant({
    'BuildWealth' : IDL.Null,
    'TrackSpending' : IDL.Null,
    'SaveForPurchase' : IDL.Null,
    'PayOffDebt' : IDL.Null,
    'Other' : IDL.Null,
    'SaveForEmergencies' : IDL.Null,
  });
  const ProfessionStatus = IDL.Variant({
    'BusinessMan' : IDL.Null,
    'Employee' : IDL.Null,
    'Student' : IDL.Null,
    'Other' : IDL.Null,
    'Freelancer' : IDL.Null,
    'Entrepreneur' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'financialGoals' : IDL.Opt(IDL.Vec(FinancialGoal)),
    'createdAt' : Timestamp,
    'professionStatus' : IDL.Opt(ProfessionStatus),
    'onboardingCompleted' : IDL.Bool,
  });
  
  return IDL.Service({
    'addExpense' : IDL.Func(
        [ExpenseId, IDL.Float64, Category, IDL.Opt(IDL.Text), Timestamp],
        [Expense],
        [],
      ),
    'createGoal' : IDL.Func(
        [GoalId, IDL.Text, IDL.Float64, IDL.Float64, Timestamp],
        [SavingsGoalPublic],
        [],
      ),
    'deleteExpense' : IDL.Func([ExpenseId], [IDL.Bool], []),
    'deleteGoal' : IDL.Func([GoalId], [IDL.Bool], []),
    'getBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
    'getBudget' : IDL.Func([], [IDL.Opt(Budget)], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getExpensesByMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getGoals' : IDL.Func([], [IDL.Vec(SavingsGoalPublic)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'saveUserProfile' : IDL.Func(
        [IDL.Opt(ProfessionStatus), IDL.Opt(IDL.Vec(FinancialGoal)), IDL.Bool],
        [],
        [],
      ),
    'setBudget' : IDL.Func([IDL.Float64, CategoryLimits], [Budget], []),
    'updateGoalProgress' : IDL.Func(
        [GoalId, IDL.Float64],
        [IDL.Opt(SavingsGoalPublic)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };