/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    financialGoals?: Array<FinancialGoal>;
    createdAt: Timestamp;
    professionStatus?: ProfessionStatus;
    onboardingCompleted: boolean;
}
export type GoalId = string;
export type Timestamp = bigint;
export interface Expense {
    id: ExpenseId;
    owner: UserId;
    date: Timestamp;
    note?: string;
    category: Category;
    amount: number;
}
export interface SavingsGoalPublic {
    id: GoalId;
    owner: UserId;
    name: string;
    targetAmount: number;
    targetDate: Timestamp;
    currentAmount: number;
}
export interface Badge {
    owner: UserId;
    badgeType: BadgeType;
    earnedAt: Timestamp;
}
export type UserId = Principal;
export type ExpenseId = string;
export interface CategoryLimits {
    other?: number;
    entertainment?: number;
    food?: number;
    transport?: number;
    bills?: number;
    shopping?: number;
    health?: number;
}
export interface Budget {
    owner: UserId;
    categoryLimits: CategoryLimits;
    totalAmount: number;
}
export enum BadgeType {
    MonthlyOnTrack = "MonthlyOnTrack",
    FirstBudget = "FirstBudget",
    LoggingStreak7 = "LoggingStreak7"
}
export enum Category {
    Food = "Food",
    Health = "Health",
    Bills = "Bills",
    Entertainment = "Entertainment",
    Shopping = "Shopping",
    Other = "Other",
    Transport = "Transport"
}
export enum FinancialGoal {
    BuildWealth = "BuildWealth",
    TrackSpending = "TrackSpending",
    SaveForPurchase = "SaveForPurchase",
    PayOffDebt = "PayOffDebt",
    Other = "Other",
    SaveForEmergencies = "SaveForEmergencies"
}
export enum ProfessionStatus {
    BusinessMan = "BusinessMan",
    Employee = "Employee",
    Student = "Student",
    Other = "Other",
    Freelancer = "Freelancer",
    Entrepreneur = "Entrepreneur"
}
export interface backendInterface {
    addExpense(id: ExpenseId, amount: number, category: Category, note: string | null, date: Timestamp): Promise<Expense>;
    createGoal(id: GoalId, name: string, targetAmount: number, currentAmount: number, targetDate: Timestamp): Promise<SavingsGoalPublic>;
    deleteExpense(id: ExpenseId): Promise<boolean>;
    deleteGoal(id: GoalId): Promise<boolean>;
    getBadges(): Promise<Array<Badge>>;
    getBudget(): Promise<Budget | null>;
    getExpenses(): Promise<Array<Expense>>;
    getExpensesByMonth(month: bigint, year: bigint): Promise<Array<Expense>>;
    getGoals(): Promise<Array<SavingsGoalPublic>>;
    getUserProfile(): Promise<UserProfile | null>;
    saveUserProfile(professionStatus: ProfessionStatus | null, financialGoals: Array<FinancialGoal> | null, onboardingCompleted: boolean): Promise<void>;
    setBudget(totalAmount: number, categoryLimits: CategoryLimits): Promise<Budget>;
    updateGoalProgress(id: GoalId, addAmount: number): Promise<SavingsGoalPublic | null>;
}
import type { Badge as _Badge, BadgeType as _BadgeType, Budget as _Budget, Category as _Category, CategoryLimits as _CategoryLimits, Expense as _Expense, ExpenseId as _ExpenseId, FinancialGoal as _FinancialGoal, ProfessionStatus as _ProfessionStatus, SavingsGoalPublic as _SavingsGoalPublic, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addExpense(arg0: ExpenseId, arg1: number, arg2: Category, arg3: string | null, arg4: Timestamp): Promise<Expense> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_Expense_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_Expense_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async createGoal(arg0: GoalId, arg1: string, arg2: number, arg3: number, arg4: Timestamp): Promise<SavingsGoalPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createGoal(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGoal(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteExpense(arg0: ExpenseId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteGoal(arg0: GoalId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGoal(arg0);
            return result;
        }
    }
    async getBadges(): Promise<Array<Badge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBadges();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBadges();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBudget(): Promise<Budget | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudget();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudget();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpensesByMonth(arg0: bigint, arg1: bigint): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesByMonth(arg0, arg1);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesByMonth(arg0, arg1);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoals(): Promise<Array<SavingsGoalPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoals();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveUserProfile(arg0: ProfessionStatus | null, arg1: Array<FinancialGoal> | null, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserProfile(to_candid_opt_n31(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserProfile(to_candid_opt_n31(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n34(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async setBudget(arg0: number, arg1: CategoryLimits): Promise<Budget> {
        if (this.processError) {
            try {
                const result = await this.actor.setBudget(arg0, to_candid_CategoryLimits_n38(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Budget_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBudget(arg0, to_candid_CategoryLimits_n38(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Budget_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGoalProgress(arg0: GoalId, arg1: number): Promise<SavingsGoalPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoalProgress(arg0, arg1);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoalProgress(arg0, arg1);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BadgeType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BadgeType): BadgeType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Badge_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Badge): Badge {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Budget_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Budget): Budget {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_CategoryLimits_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryLimits): CategoryLimits {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Expense_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_FinancialGoal_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FinancialGoal): FinancialGoal {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ProfessionStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfessionStatus): ProfessionStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Budget]): Budget | null {
    return value.length === 0 ? null : from_candid_Budget_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_FinancialGoal>]): Array<FinancialGoal> | null {
    return value.length === 0 ? null : from_candid_vec_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfessionStatus]): ProfessionStatus | null {
    return value.length === 0 ? null : from_candid_ProfessionStatus_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SavingsGoalPublic]): SavingsGoalPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: _UserId;
    badgeType: _BadgeType;
    earnedAt: _Timestamp;
}): {
    owner: UserId;
    badgeType: BadgeType;
    earnedAt: Timestamp;
} {
    return {
        owner: value.owner,
        badgeType: from_candid_BadgeType_n12(_uploadFile, _downloadFile, value.badgeType),
        earnedAt: value.earnedAt
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: _UserId;
    categoryLimits: _CategoryLimits;
    totalAmount: number;
}): {
    owner: UserId;
    categoryLimits: CategoryLimits;
    totalAmount: number;
} {
    return {
        owner: value.owner,
        categoryLimits: from_candid_CategoryLimits_n17(_uploadFile, _downloadFile, value.categoryLimits),
        totalAmount: value.totalAmount
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: [] | [number];
    entertainment: [] | [number];
    food: [] | [number];
    transport: [] | [number];
    bills: [] | [number];
    shopping: [] | [number];
    health: [] | [number];
}): {
    other?: number;
    entertainment?: number;
    food?: number;
    transport?: number;
    bills?: number;
    shopping?: number;
    health?: number;
} {
    return {
        other: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.other)),
        entertainment: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.entertainment)),
        food: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.food)),
        transport: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.transport)),
        bills: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.bills)),
        shopping: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.shopping)),
        health: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.health))
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    financialGoals: [] | [Array<_FinancialGoal>];
    createdAt: _Timestamp;
    professionStatus: [] | [_ProfessionStatus];
    onboardingCompleted: boolean;
}): {
    financialGoals?: Array<FinancialGoal>;
    createdAt: Timestamp;
    professionStatus?: ProfessionStatus;
    onboardingCompleted: boolean;
} {
    return {
        financialGoals: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.financialGoals)),
        createdAt: value.createdAt,
        professionStatus: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.professionStatus)),
        onboardingCompleted: value.onboardingCompleted
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ExpenseId;
    owner: _UserId;
    date: _Timestamp;
    note: [] | [string];
    category: _Category;
    amount: number;
}): {
    id: ExpenseId;
    owner: UserId;
    date: Timestamp;
    note?: string;
    category: Category;
    amount: number;
} {
    return {
        id: value.id,
        owner: value.owner,
        date: value.date,
        note: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.note)),
        category: from_candid_Category_n7(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    MonthlyOnTrack: null;
} | {
    FirstBudget: null;
} | {
    LoggingStreak7: null;
}): BadgeType {
    return "MonthlyOnTrack" in value ? BadgeType.MonthlyOnTrack : "FirstBudget" in value ? BadgeType.FirstBudget : "LoggingStreak7" in value ? BadgeType.LoggingStreak7 : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    BuildWealth: null;
} | {
    TrackSpending: null;
} | {
    SaveForPurchase: null;
} | {
    PayOffDebt: null;
} | {
    Other: null;
} | {
    SaveForEmergencies: null;
}): FinancialGoal {
    return "BuildWealth" in value ? FinancialGoal.BuildWealth : "TrackSpending" in value ? FinancialGoal.TrackSpending : "SaveForPurchase" in value ? FinancialGoal.SaveForPurchase : "PayOffDebt" in value ? FinancialGoal.PayOffDebt : "Other" in value ? FinancialGoal.Other : "SaveForEmergencies" in value ? FinancialGoal.SaveForEmergencies : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    BusinessMan: null;
} | {
    Employee: null;
} | {
    Student: null;
} | {
    Other: null;
} | {
    Freelancer: null;
} | {
    Entrepreneur: null;
}): ProfessionStatus {
    return "BusinessMan" in value ? ProfessionStatus.BusinessMan : "Employee" in value ? ProfessionStatus.Employee : "Student" in value ? ProfessionStatus.Student : "Other" in value ? ProfessionStatus.Other : "Freelancer" in value ? ProfessionStatus.Freelancer : "Entrepreneur" in value ? ProfessionStatus.Entrepreneur : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Food: null;
} | {
    Health: null;
} | {
    Bills: null;
} | {
    Entertainment: null;
} | {
    Shopping: null;
} | {
    Other: null;
} | {
    Transport: null;
}): Category {
    return "Food" in value ? Category.Food : "Health" in value ? Category.Health : "Bills" in value ? Category.Bills : "Entertainment" in value ? Category.Entertainment : "Shopping" in value ? Category.Shopping : "Other" in value ? Category.Other : "Transport" in value ? Category.Transport : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FinancialGoal>): Array<FinancialGoal> {
    return value.map((x)=>from_candid_FinancialGoal_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Badge>): Array<Badge> {
    return value.map((x)=>from_candid_Badge_n10(_uploadFile, _downloadFile, x));
}
function to_candid_CategoryLimits_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CategoryLimits): _CategoryLimits {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_FinancialGoal_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FinancialGoal): _FinancialGoal {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_ProfessionStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfessionStatus): _ProfessionStatus {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfessionStatus | null): [] | [_ProfessionStatus] {
    return value === null ? candid_none() : candid_some(to_candid_ProfessionStatus_n32(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FinancialGoal> | null): [] | [Array<_FinancialGoal>] {
    return value === null ? candid_none() : candid_some(to_candid_vec_n35(_uploadFile, _downloadFile, value));
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other?: number;
    entertainment?: number;
    food?: number;
    transport?: number;
    bills?: number;
    shopping?: number;
    health?: number;
}): {
    other: [] | [number];
    entertainment: [] | [number];
    food: [] | [number];
    transport: [] | [number];
    bills: [] | [number];
    shopping: [] | [number];
    health: [] | [number];
} {
    return {
        other: value.other ? candid_some(value.other) : candid_none(),
        entertainment: value.entertainment ? candid_some(value.entertainment) : candid_none(),
        food: value.food ? candid_some(value.food) : candid_none(),
        transport: value.transport ? candid_some(value.transport) : candid_none(),
        bills: value.bills ? candid_some(value.bills) : candid_none(),
        shopping: value.shopping ? candid_some(value.shopping) : candid_none(),
        health: value.health ? candid_some(value.health) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    Food: null;
} | {
    Health: null;
} | {
    Bills: null;
} | {
    Entertainment: null;
} | {
    Shopping: null;
} | {
    Other: null;
} | {
    Transport: null;
} {
    return value == Category.Food ? {
        Food: null
    } : value == Category.Health ? {
        Health: null
    } : value == Category.Bills ? {
        Bills: null
    } : value == Category.Entertainment ? {
        Entertainment: null
    } : value == Category.Shopping ? {
        Shopping: null
    } : value == Category.Other ? {
        Other: null
    } : value == Category.Transport ? {
        Transport: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfessionStatus): {
    BusinessMan: null;
} | {
    Employee: null;
} | {
    Student: null;
} | {
    Other: null;
} | {
    Freelancer: null;
} | {
    Entrepreneur: null;
} {
    return value == ProfessionStatus.BusinessMan ? {
        BusinessMan: null
    } : value == ProfessionStatus.Employee ? {
        Employee: null
    } : value == ProfessionStatus.Student ? {
        Student: null
    } : value == ProfessionStatus.Other ? {
        Other: null
    } : value == ProfessionStatus.Freelancer ? {
        Freelancer: null
    } : value == ProfessionStatus.Entrepreneur ? {
        Entrepreneur: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FinancialGoal): {
    BuildWealth: null;
} | {
    TrackSpending: null;
} | {
    SaveForPurchase: null;
} | {
    PayOffDebt: null;
} | {
    Other: null;
} | {
    SaveForEmergencies: null;
} {
    return value == FinancialGoal.BuildWealth ? {
        BuildWealth: null
    } : value == FinancialGoal.TrackSpending ? {
        TrackSpending: null
    } : value == FinancialGoal.SaveForPurchase ? {
        SaveForPurchase: null
    } : value == FinancialGoal.PayOffDebt ? {
        PayOffDebt: null
    } : value == FinancialGoal.Other ? {
        Other: null
    } : value == FinancialGoal.SaveForEmergencies ? {
        SaveForEmergencies: null
    } : value;
}
function to_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FinancialGoal>): Array<_FinancialGoal> {
    return value.map((x)=>to_candid_FinancialGoal_n36(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
